project_id = "uqinkqqxuhcwgumhvzoj"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.get-weather]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.send-call-sheet-notification]
    verify_jwt = false
